language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: mark@segfawlt.net
  api_key:
    secure: c2p1lp2MGNrIkSItrPXaHzW9FxI1XewDuxC1Qy5bv0Y0VcOeyuhGxv7Vl0rIe7HkSwTaMKTXnx+B7tDleqfsuEvJVIWflKy+JVTBqsPJtaoaHrqnBTaqDbJZlA5+2qNj+kW2vTMeYgN1ITy4EO9ZF4lW3h02efw2uHyYX+YmGMs=
  on:
    tags: true
    repo: markhuge/posicon-hipchat
    all_branches: true
